### ISSUE TITLE
严格模式的拼音方案

### ISSUE THREAD

**Issue by LuoZijun** [mozillazg/rust-pinyin#23]
原型代码: https://github.com/luozijun/rust-pinyin/tree/patch-2/src

这是一份未完成的原型代码，旨在完整严格实现 `汉语拼音方案` 。

目前没有任何依赖，可以使用 每日构建版 Rust 编译器直接编译(rustc pinyin.rs)。

对整个的代码改动非常大，不知是否有兴趣合并？

**Comment by mozillazg** [comment]
@LuoZijun 👍 继续用已存在的 `pinyin` 这个函数名可能不大好，因为可能需要考虑兼容旧版用法的问题。还是说是打算完全不兼容旧版完全重写整个项目？

**Comment by LuoZijun** [comment]
@mozillazg 

原型代码更新了下，已经接近可用状态。

体验:
```sh
git clone https://github.com/LuoZijun/rust-pinyin.git
cd rust-pinyin
git checkout patch-2

cargo run
```

我的设计是 希望函数返回的是一个 结构化的 拼音信息，
然后用户根据这个拼音结构去做些其它的操作（比如 获取声母/韵母/韵头/韵腹, 判断音节类别等）。

至于 `pinyin` 函数命名，我觉得可以再想想。

简单用法:

```rust
extern crate pinyin;

use pinyin::{
    PinYin,
    Tone, ToneMark,
    Initial, Rhyme,
    Syllable, SyllableKind,
    PrimitiveSyllable, NormalSyllable, RhymeSyllable, NasalSyllable,
};


fn main() {
    let word: char = '我';
    for syllable in word.pinyin() {
        println!("Syllable: {:?}", syllable);
        println!("Vowel: {:?}", syllable.vowel());
        println!("Tone: {:?}", syllable.tone());
        println!("ToneMark: {:?}", syllable.tone_mark());
    }
    println!("");
}

```

设计:

`PinYin` 是一个 `trait` ，
这个 `trait` 有一个 `pinyin` 函数名称(因为使用了 trait ，所以跟原本的不冲突) 。

默认 为 标准库当中的 `char` 类型实现了 `PinYin` 特性。也就是意味着 `char` 类型可以直接有 `pinyin()` 方法。

做这样的设计，是因为 `音节` 结构是多样化的，所以对于`分词库` 来讲，他可以定义汉字里面 `词` 的结构，然后为这个结构 实现 `pinyin` 方法。

`Syllable` 也是一个 `trait`.
目前实现了四个音节结构: PrimitiveSyllable, NormalSyllable, RhymeSyllable, NasalSyllable.
这四个音节结构都实现了 `Syllable` 特性。

最后，也想听听你对这个代码原型设计的意见。

**Comment by LuoZijun** [comment]
更新了下原型代码，增加了 字典文件(`dict.rs`).

体验使用: `cargo run --example query`
文档查看: `cargo doc; open target/doc/pinyin/index.html`

**Comment by LuoZijun** [comment]
@mozillazg 目前几乎实现了所有的 拼音替换补写规则。

不知道你对这个有什么看法？

另外，我注意到你有一个 汉语词汇 的拼音字典，如果这些拼音规则实现妥当，我想，多个汉字音节连在一起也是可以水到渠成的，并且不依赖字典文件 可以实现 诸如 `花儿` -> `huar` 。

**Comment by mozillazg** [comment]
@LuoZijun 为设计点赞，灵活性很高。为可以做到 【做这样的设计，是因为 音节 结构是多样化的，所以对于分词库 来讲，他可以定义汉字里面 词 的结构，然后为这个结构 实现 pinyin 方法。】这样点赞 👍
