### ISSUE TITLE
[讨论] 日本汉字的汉语读音规范

### ISSUE THREAD

**Issue by LuoZijun** [mozillazg/rust-pinyin#30]
日本汉字的汉语读音规范: http://www.moe.gov.cn/s78/A19/yxs_left/moe_810/s230/201001/t20100115_75698.html

例子(来自 Unicode-UCD数据库):

```
匂 U+21250
    kHanyuPinyin    10418.040:chūn
    kMandarin   chūn

丼 U+20028
    kVietnamese cụp

```

**Comment by mozillazg** [comment]
下面那个 `丼` 是日本汉字？是讨论支持对日本汉字标注拼音？

**Comment by LuoZijun** [comment]
@mozillazg 应该仅仅指日本自造汉字的拼音标注。日本自造汉字和我们并没有冲突。

**Comment by LuoZijun** [comment]
@mozillazg 至于 `丼` 字，这个草案里面提到了，这是日本工具书认定它为日本自造汉字（工具书也并非是没有错误的），但是其实在我们古籍里面就有这个汉字，也就是说，这个字并非日本自造的。

**Comment by mozillazg** [comment]
@LuoZijun 嗯，可以支持日本自造汉字的拼音标注。似乎只需要更新 https://github.com/mozillazg/pinyin-data 增加【日本汉字的汉语读音规范表】中的那 32 个日本自造汉字的拼音就可以了？ 还是说再找找这 32 个常用日本自造汉字以外的其他日本自造汉字（简单搜了一下没搜到），然后按照《日本汉字的汉语读音规范》里的规范增加拼音？

**Comment by LuoZijun** [comment]
目前好像就只有这几个字，也许草案最好发布的时候，会有更多也不一定。不过我不懂日语这些，也不太清楚。

**Comment by LuoZijun** [comment]
相关意见和讨论可以移步: https://github.com/mozillazg/pinyin-data/issues/32
PR: https://github.com/mozillazg/pinyin-data/pull/33
