### ISSUE TITLE
部分非常见拼音在数字调号时依然使用音调符号

### ISSUE THREAD

**Issue by upsuper** [mozillazg/rust-pinyin#45]
见 [#44 (comment)](https://github.com/mozillazg/rust-pinyin/pull/44#issuecomment-500131850)，如ê̄, ê̌, m̄, m̀。

**Comment by LuoZijun** [comment]
涉及: `ê̄`, `ê̌`, `m̄`, `m̀` 。

**Comment by mozillazg** [comment]
@LuoZijun 感谢发现，之前没注意到 ê̄, ê̌, m̄, m̀ 这些特殊字符。

**Comment by upsuper** [comment]
Fixed by #51.
