### ISSUE TITLE
[讨论] 字母 ü 是否需要转写成 v ？

### ISSUE THREAD

**Issue by LuoZijun** [mozillazg/rust-pinyin#49]
这个可能需要 @mozillazg 出来说一下这个。

如果需要按照之前的做法去转写的话，那么这里可能就有一个风格统一问题。
`吕` 和 `女`  字的拼音在不同声调输出样式下分别为:

*    `lv`, `nv`
*    `lv3`, `nv3`
*    `lǚ`, `nǚ`

这样看起来，风格似乎有出入 ？

导致这个风格不统一的原因在于 当拼音数据以 `数字声调` 标记方式来标记的话，字母 `ü` 被替换成了 `v` ，但是以 `声调符号` 标记方式来标记的话，则没有做任何处理。

**Comment by mozillazg** [comment]
@LuoZijun 这个算是当时实现的一个约定，没有声调的风格下都使用 v 代替 ü，如果大家觉得之前的那个使用 v 代替 ü 的约定不好的话，可以在下个版本中修正为更符合规范/预期的结果？
